# -*- coding: utf-8 -*-
"""Accelerating pandas with GPU.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hUSCnKg7czDQ29T1rh9rNLBYev2Omt6Z
"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext cudf.pandas
import pandas as pd
import random

# Define the species categories
species_categories = ['setosa', 'versicolor', 'virginica']
flower_color_categories = ['red','yellow','green']

# Define the range for each attribute based on typical iris flower measurements
sepal_length_range = (4.0, 8.0)

# Create data for 1,000,000 samples
n = 1000000
data = {
    'sepal_length': [random.uniform(*sepal_length_range) for _ in range(n)],
    'flower_color': [random.choice(flower_color_categories) for _ in range(n)],
    'species': [random.choice(species_categories) for _ in range(n)]
}

df = pd.DataFrame(data)

df.groupby(['species','flower_color']).size().sort_values(ascending=False)

# Commented out IPython magic to ensure Python compatibility.
# %load_ext cudf.pandas
import pandas as pd
import numpy as np

# Define the number of rows
num_rows = 1000000

states = ["NY", "NJ", "CA", "TX"]
violations = ["Double Parking", "Expired Meter", "No Parking", "Fire Hydrant",
              "Bus Stop"]
vehicle_types = ["SUBN", "SDN"]

# Generate random data for Dataset 1
data1 = {
    "Registration State": np.random.choice(states, size=num_rows),
    "Ticket Number": np.random.randint(1000000000, 9999999999, size=num_rows)
}

# Generate random data for Dataset 2
data2 = {
    "Ticket Number": np.random.choice(data1['Ticket Number'], size=num_rows),  # Reusing ticket numbers to ensure matches
    "Violation Description": np.random.choice(violations, size=num_rows)
}

# Create DataFrames
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

# Perform an inner join on 'Ticket Number'
merged_df = pd.merge(df1, df2, on="Ticket Number", how="inner")

# Display some of the joined data
print(merged_df.head())

# Commented out IPython magic to ensure Python compatibility.
# %load_ext cudf.pandas
import pandas as pd
import numpy as np

import pandas as pd
import numpy as np

# Define the number of rows
num_rows = 1000000

# Define the possible values
states = ["NY", "NJ", "CA", "TX"]
violations = ["Double Parking", "Expired Meter", "No Parking", "Fire Hydrant", "Bus Stop"]
vehicle_types = ["SUBN", "SDN"]

start_date = "2022-01-01"
end_date = "2022-12-31"
# Create a date range
dates = pd.date_range(start=start_date, end=end_date, freq='D')

# Generate random data
data = {
    "Registration State": np.random.choice(states, size=num_rows),
    "Violation Description": np.random.choice(violations, size=num_rows),
    "Vehicle Body Type": np.random.choice(vehicle_types, size=num_rows),
    "Issue Date": np.random.choice(dates, size=num_rows),
    "Ticket Number": np.random.randint(1000000000, 9999999999, size=num_rows)
}

# Create a DataFrame
df = pd.DataFrame(data)

# Adding issue weekday based on the "Issue Date"
weekday_names = {
    0: "Monday",
    1: "Tuesday",
    2: "Wednesday",
    3: "Thursday",
    4: "Friday",
    5: "Saturday",
    6: "Sunday",
}

df["issue_weekday"] = df["Issue Date"].dt.weekday.map(weekday_names)

# Grouping by issue_weekday and counting the Summons Number
df.groupby(["Issue Date"])["Ticket Number"
].count().sort_values()

# Commented out IPython magic to ensure Python compatibility.
# %load_ext cudf.pandas
import pandas as pd
import numpy as np

# Randomly generated dataset of parking violations-
# Define the number of rows
num_rows = 1000000

states = ["NY", "NJ", "CA", "TX"]
violations = ["Double Parking", "Expired Meter", "No Parking",
              "Fire Hydrant", "Bus Stop"]
vehicle_types = ["SUBN", "SDN"]

# Create a date range
start_date = "2022-01-01"
end_date = "2022-12-31"
dates = pd.date_range(start=start_date, end=end_date, freq='D')

# Generate random data
data = {
    "Registration State": np.random.choice(states, size=num_rows),
    "Violation Description": np.random.choice(violations, size=num_rows),
    "Vehicle Body Type": np.random.choice(vehicle_types, size=num_rows),
    "Issue Date": np.random.choice(dates, size=num_rows),
    "Ticket Number": np.random.randint(1000000000, 9999999999, size=num_rows)
}

# Create a DataFrame
df = pd.DataFrame(data)

# Which parking violation is most commonly committed by vehicles from various U.S states?

(df[["Registration State", "Violation Description"]]  # get only these two columns
 .value_counts()  # get the count of offences per state and per type of offence
 .groupby("Registration State")  # group by state
 .head(1)  # get the first row in each group (the type of offence with the largest count)
 .sort_index()  # sort by state name
 .reset_index()
)

